
@auth_token = {{get_auth_token.response.body.data}}
@created_category_id = {{create_categories.response.body.data.id}}
@category_id = {{get_categories.response.body.data[0].id}}


###
# @name get_auth_token
GET {{protocol}}://{{auth-domain}}/auth
?key={{key}}
&secret={{secret}}


###
# @name create_categories   
POST {{protocol}}://{{domain}}/categories
Authorization: {{auth_token}}
content-type: application/json

{
    "label":"Test"
}


###
# @name get_categories
GET {{protocol}}://{{domain}}/categories
Authorization: {{auth_token}}


###
# @name retrieve_category
GET {{protocol}}://{{domain}}/categories/{{created_category_id}}
Authorization: {{auth_token}}

###
# @name retrieve_category_attributes
GET {{protocol}}://{{domain}}/categories/{{category_id}}/attributes
Authorization: {{auth_token}}


###
# @name update_category
PUT {{protocol}}://{{domain}}/categories/{{category_id}}
Authorization: {{auth_token}}
content-type: application/json

{
    "label":"Test category"
}


###
# @name delete_category
DELETE {{protocol}}://{{domain}}/categories/{{created_category_id}}
Authorization: {{auth_token}}
