
@zone_id = 1
@crop_id = 1

###
# @name get_crops_zone_attributes
GET {{protocol}}://{{domain}}/zones/{{zone_id}}/crops/{{crop_id}}


###
# ( Legacy Data Object )
# @name get_bulk_crop_data
GET {{protocol}}://{{domain}}/crop-data?zoneId=1



