

###
# @name get_requests
GET {{protocol}}://{{domain}}/requests

###
# @name create_requests
POST {{protocol}}://{{domain}}/requests
Content-Type: application/json

{
    "service":"test-service",
    "method": "req.method",
    "uri": "req.url",
    "clientIp": "req.headers['x-forwarded-for'] ?? req.ip",
    "clientUserAgent": "req.headers['user-agent'] ?? 'unknown'",
    "contentType": "req.headers['content-type'] ?? 'n/a'",
    "authorization": "req.headers['authorization'] ?? 'n/a'",
    "headers": "JSON.stringify(req.headers)",
    "params": "JSON.stringify(req.query)",
    "body": "body"
}


