INSERT INTO crops_shape_and_orientation (crop_id, shape_and_orientation_id) VALUES
((SELECT id FROM crops WHERE label = 'Soybeans' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Triticale, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Mustard' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Triticale, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Berseem' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Crimson' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cereal Rye, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Phacelia' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Red' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, White' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Radish, Oilseed' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Brassica, Forage' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Ryegrass, Annual' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Radish, Forage' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sorghum-sudangrass' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Wheat, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sweetclover, Yellow' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Teff' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Rape, Oilseed, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Wheat, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Barley, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cereal Rye, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Balansa' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cowpea' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Millet, Japanese' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sunflower' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sunn Hemp' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Vetch, Hairy' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Cowpea' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Alfalfa, Dormant' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Rape, Oilseed, Spring' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Oats, Black' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Barley, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, White' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Prostrate')),
((SELECT id FROM crops WHERE label = 'Pea, Winter' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Buckwheat' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sudangrass' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Oats' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Corn' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Millet, Pearl' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Buckwheat' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Crimson' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Sorghum' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Turnip, Forage' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Ryegrass, Perennial' and zone = 5),(SELECT id FROM shape_and_orientation WHERE label = 'Erect'));
