INSERT INTO crops_shape_and_orientation (crop_id, shape_and_orientation_id) VALUES
((SELECT id FROM crops WHERE label = 'Buckwheat' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Red' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Millet, Pearl' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Soybeans' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Clover, Crimson' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Triticale, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Alfalfa, Dormant' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cereal Rye, Spring' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sunn Hemp' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sorghum' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Buckwheat' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Radish, Forage' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Ryegrass, Annual' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Spring' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Vetch, Hairy' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Wheat, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cowpea' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Cowpea' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Clover, Crimson' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Oats, Spring' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Barley, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Climbing')),
((SELECT id FROM crops WHERE label = 'Rapeseed, Forage' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Mustard' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Cereal Rye, Winter' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sorghum-sudangrass' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Pea, Spring' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Semi-Erect')),
((SELECT id FROM crops WHERE label = 'Oats' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect')),
((SELECT id FROM crops WHERE label = 'Sunflower' and zone = 7),(SELECT id FROM shape_and_orientation WHERE label = 'Erect'));
