INSERT INTO  "legacy".data_keys (label, key) VALUES
('_id','_id'),
('Reduces Surface Compaction','reduces_surface_compaction'),
('Nitrogen Scavenging','nitrogen_scavenging'),
('Chemical Termination at Vegetative','chemical_termination_at_vegetative'),
('Improve Soil Organic Matter','improve_soil_organic_matter'),
('Drilled Depth Max','drilled_depth_max'),
('Root Depth','root_depth'),
('Standard Spring Seeding Rate Start','standard_spring_seeding_rate_start'),
('Prevent Spring Soil Erosion','prevent_spring_soil_erosion'),
('Dry Matter Max (lbs/A/y)','dry_matter_max_(lbs/a/y)'),
('Chemical Termination at Flowering','chemical_termination_at_flowering'),
('C to N Ratio','c_to_n_ratio'),
('Notes: Basic Agronomics','notes:_basic_agronomics'),
('Family Scientific Name','family_scientific_name'),
('cv, var, or ssp to specify','cv__var__or_ssp_to_specify'),
('Penetrates Plow Pan','penetrates_plow_pan'),
('Notes: Weeds','notes:_weeds'),
('Notes: Forage and Grazing','notes:_forage_and_grazing'),
('Supresses Winter Annual Weeds','supresses_winter_annual_weeds'),
('Tillage Termination at Vegetative','tillage_termination_at_vegetative'),
('Freezing Termination at Vegetative','freezing_termination_at_vegetative'),
('Mow Termination at Flowering','mow_termination_at_flowering'),
('Flood Tolerance','flood_tolerance'),
('Prevent Fall Soil Erosion','prevent_fall_soil_erosion'),
('Shade Tolerance','shade_tolerance'),
('Reliable Establishment/Growth Start','reliable_establishment/growth_start'),
('Nitrogen Accumulation Max, Legumes (lbs/A/y)','nitrogen_accumulation_max__legumes_(lbs/a/y)'),
('Forage Harvest Value','forage_harvest_value'),
('Drilled Depth Min','drilled_depth_min'),
('Salinity Tolerance','salinity_tolerance'),
('Roller Crimp Termination at Flowering','roller_crimp_termination_at_flowering'),
('Standard Summer Seeding Rate End','standard_summer_seeding_rate_end'),
('Reliable Establishment/Growth End','reliable_establishment/growth_end'),
('ITIS TSN','itis_tsn'),
('Persistence','persistence'),
('Nitrogen Accumulation Min, Legumes (lbs/A/y)','nitrogen_accumulation_min__legumes_(lbs/a/y)'),
('Cover Crop Group','cover_crop_group'),
('Flooding Frequency Tolerance','flooding_frequency_tolerance'),
('Residue Supresses Summer Annual Weeds','residue_supresses_summer_annual_weeds'),
('Standard Spring Seeding Rate End','standard_spring_seeding_rate_end'),
('Standard Summer Seeding Rate Start','standard_summer_seeding_rate_start'),
('Outcompetes Summer Annual Weeds','outcompetes_summer_annual_weeds'),
('Origin','origin'),
('Pollinator Food','pollinator_food'),
('Low Fertility Tolerance','low_fertility_tolerance'),
('Min Germination Temp (F)','min_germination_temp_(f)'),
('Scientific Name','scientific_name'),
('Growing Window','growing_window'),
('Heat Tolerance','heat_tolerance'),
('Seed Price per Pound','seed_price_per_pound'),
('Cover Crop Description','cover_crop_description'),
('Early Spring Growth','early_spring_growth'),
('Zone Decision','zone_decision'),
('Base Seeding Rate Max (lbs/A)','base_seeding_rate_max_(lbs/a)'),
('Notes: Goals','notes:_goals'),
('Maximum Tolerant Soil pH','maximum_tolerant_soil_ph'),
('Drought Tolerance','drought_tolerance'),
('Family Common Name','family_common_name'),
('Cover Crop Name','cover_crop_name'),
('Volunteer Establishment','volunteer_establishment'),
('Lasting Residue','lasting_residue'),
('Seeds per Pound','seeds_per_pound'),
('Base Seeding Rate Min (lbs/A)','base_seeding_rate_min_(lbs/a)'),
('Soil Moisture Use','soil_moisture_use'),
('Minimum Tolerant Soil pH','minimum_tolerant_soil_ph'),
('Dry Matter Min (lbs/A/y)','dry_matter_min_(lbs/a/y)'),
('Good Grazing','good_grazing'),
('Zone Use','zone_use'),
('Zone','zone'),
('Tillage Termination at Flowering','tillage_termination_at_flowering'),
('Ease of Establishment','ease_of_establishment'),
('Increase Soil Aggregation','increase_soil_aggregation'),
('Supports Mycorrhizae','supports_mycorrhizae'),
('Establishes Quickly','establishes_quickly'),
('USDA Symbol','usda_symbol'),
('__id','__id'),
('Standard Fall Seeding Rate Start','standard_fall_seeding_rate_start'),
('Notes: Insects','notes:_insects'),
('Standard Fall Seeding Rate End','standard_fall_seeding_rate_end'),
('Reduces Crusting','reduces_crusting'),
('Notes: Environmental Tolerances','notes:_environmental_tolerances'),
('Notes: Nematodes','notes:_nematodes'),
('Notes: Pollinators','notes:_pollinators'),
('Synonyms','synonyms'),
('Notes: Planting','notes:_planting'),
('Temperature/Moisture Risk to Establishment Start','temperature/moisture_risk_to_establishment_start'),
('Temperature/Moisture Risk to Establishment End','temperature/moisture_risk_to_establishment_end'),
('Late Fall Seeding Rate End','late_fall_seeding_rate_end'),
('Late Fall Seeding Rate Start','late_fall_seeding_rate_start'),
('Can Aerial Seed?','can_aerial_seed?'),
('Notes: Termination','notes:_termination'),
('Nitrogen Fixation','nitrogen_fixation'),
('Search Synonyms','search_synonyms'),
('Second Reliable Establishment/Growth End','second_reliable_establishment/growth_end'),
('Frost Seeding Start','frost_seeding_start'),
('Second Reliable Establishment/Growth Start','second_reliable_establishment/growth_start'),
('Frost Seeding End','frost_seeding_end'),
('Notes: Growth, Roots, and Nutrients','notes:_growth__roots__and_nutrients'),
('Frost Seeding','frost_seeding'),
('Notes: Taxonomy','notes:_taxonomy'),
('Notes: Disease','notes:_disease'),
('Notes: Soil Conditions','notes:_soil_conditions'),
('Hessian Fly-Free Date','hessian_fly-free_date'),
('Early Fall/Winter Seeding Rate Start','early_fall/winter_seeding_rate_start'),
('Early Fall/Winter Seeding Rate End','early_fall/winter_seeding_rate_end'),
('Standard Fall/Winter Seeding Rate Start','standard_fall/winter_seeding_rate_start'),
('Standard Fall/Winter Seeding Rate End','standard_fall/winter_seeding_rate_end'),
('Late Fall/Winter Seeding Rate Start','late_fall/winter_seeding_rate_start'),
('Late Fall/Winter Seeding Rate End','late_fall/winter_seeding_rate_end'),
('Residue Suppresses Summer Annual Weeds','residue_suppresses_summer_annual_weeds'),
('Suppresses Winter Annual Weeds','suppresses_winter_annual_weeds'),
('Search Synonym','search_synonym'),
('Second Temperature/Moisture Risk to Establishment Start','second_temperature/moisture_risk_to_establishment_start'),
('Second Temperature/Moisture Risk to Establishment End','second_temperature/moisture_risk_to_establishment_end'),
('Freezing Termination at Flowering','freezing_termination_at_flowering'),
('Early Spring Seeding Rate Start','early_spring_seeding_rate_start'),
('Early Spring Seeding Rate End','early_spring_seeding_rate_end'),
('Appearance','appearance'),
('License','license'),
('Zone Cover Crop Description','zone_cover_crop_description'),
('Late Summer Seeding Rate Start','late_summer_seeding_rate_start'),
('Late Summer Seeding Rate End','late_summer_seeding_rate_end'),
('Can Aerial Seed','can_aerial_seed'),
('Can Interseed Start','can_interseed_start'),
('Can Interseed End','can_interseed_end'),
('Standard Fall/Winter Seeding Rate Date End','standard_fall/winter_seeding_rate_date_end'),
('Roller Crimp Tolerance at Flowering','roller_crimp_tolerance_at_flowering'),
('Late Fall/Winter Seeding Rate Date Start','late_fall/winter_seeding_rate_date_start'),
('Standard Fall/Winter Seeding Rate Date Start','standard_fall/winter_seeding_rate_date_start'),
('Late Fall/Winter Seeding Rate Date End','late_fall/winter_seeding_rate_date_end'),
('Standard Summer Seeding Rate Date End','standard_summer_seeding_rate_date_end'),
('Standard Summer Seeding Rate Date Start','standard_summer_seeding_rate_date_start'),
('Standard Spring Seeding Rate Date Start','standard_spring_seeding_rate_date_start'),
('Standard Spring Seeding Rate Date End','standard_spring_seeding_rate_date_end');