INSERT INTO  "legacy".crops (label, zone) VALUES
('Barley, Spring',4),
('Barley, Winter',4),
('Buckwheat',4),
('Cereal Rye, Winter',4),
('Clover, Alsike',4),
('Clover, Berseem',4),
('Clover, Crimson',4),
('Clover, Red',4),
('Clover, White',4),
('Cowpea',4),
('Millet, Japanese',4),
('Millet, Pearl',4),
('Mustard',4),
('Oats',4),
('Pea, Spring',4),
('Pea, Winter',4),
('Radish, Forage',4),
('Radish, Oilseed',4),
('Rape, Oilseed, Spring',4),
('Rape, Oilseed, Winter',4),
('Ryegrass, Annual',4),
('Ryegrass, Perennial',4),
('Sorghum',4),
('Sorghum-sudangrass',4),
('Soybeans',4),
('Sudangrass',4),
('Sunflower',4),
('Sunn Hemp',4),
('Sweetclover, Yellow',4),
('Teff',4),
('Triticale, Spring',4),
('Triticale, Winter',4),
('Turnip, Forage',4),
('Vetch, Hairy',4),
('Wheat, Spring',4),
('Wheat, Winter',4),
('__Open Discussion Row',5),
('Alfalfa, Dormant',5),
('Barley, Spring',5),
('Barley, Winter',5),
('Brassica, Forage',5),
('Buckwheat',5),
('Cereal Rye, Spring',5),
('Cereal Rye, Winter',5),
('Clover, Balansa',5),
('Clover, Berseem',5),
('Clover, Crimson',5),
('Clover, Red',5),
('Clover, White',5),
('Corn',5),
('Cowpea',5),
('Millet, Japanese',5),
('Millet, Pearl',5),
('Mustard',5),
('Oats',5),
('Oats, Black',5),
('Pea, Spring',5),
('Pea, Winter',5),
('Phacelia',5),
('Radish, Forage',5),
('Radish, Oilseed',5),
('Rape, Oilseed, Spring',5),
('Rape, Oilseed, Winter',5),
('Ryegrass, Annual',5),
('Ryegrass, Perennial',5),
('Sorghum',5),
('Sorghum-sudangrass',5),
('Soybeans',5),
('Sudangrass',5),
('Sunflower',5),
('Sunn Hemp',5),
('Sweetclover, Yellow',5),
('Teff',5),
('Triticale, Spring',5),
('Triticale, Winter',5),
('Turnip, Forage',5),
('Vetch, Hairy',5),
('Wheat, Spring',5),
('Wheat, Winter',5),
('__Open Discussion Row',6),
('Barley, Spring',6),
('Barley, Winter',6),
('Brassica, Forage',6),
('Buckwheat',6),
('Cereal Rye, Spring',6),
('Cereal Rye, Winter',6),
('Clover, Balansa',6),
('Clover, Berseem',6),
('Clover, Crimson',6),
('Clover, Red',6),
('Cowpea',6),
('Millet, Japanese',6),
('Millet, Pearl',6),
('Mustard',6),
('Oats',6),
('Oats, Black',6),
('Oats, Spring',6),
('Pea, Spring',6),
('Pea, Winter',6),
('Phacelia',6),
('Radish, Forage',6),
('Rapeseed, Forage',6),
('Ryegrass, Annual',6),
('Ryegrass, Perennial',6),
('Sorghum-sudangrass',6),
('Soybeans',6),
('Sudangrass',6),
('Sunflower',6),
('Sunn Hemp',6),
('Sweetclover, Yellow',6),
('Teff',6),
('Triticale, Spring',6),
('Triticale, Winter',6),
('Turnip, Forage',6),
('Turnip, Purple Top',6),
('Vetch, Hairy',6),
('Wheat, Spring',6),
('Wheat, Winter',6),
('Alfalfa, Dormant',7),
('Barley, Winter',7),
('Buckwheat',7),
('Cereal Rye, Spring',7),
('Cereal Rye, Winter',7),
('Clover, Crimson',7),
('Clover, Red',7),
('Cowpea',7),
('Millet, Pearl',7),
('Mustard',7),
('Oats',7),
('Oats, Spring',7),
('Pea, Spring',7),
('Pea, Winter',7),
('Radish, Forage',7),
('Rapeseed, Forage',7),
('Ryegrass, Annual',7),
('Sorghum',7),
('Sorghum-sudangrass',7),
('Soybeans',7),
('Sunflower',7),
('Sunn Hemp',7),
('Triticale, Winter',7),
('Vetch, Hairy',7),
('Wheat, Winter',7);